[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://www.metaweather.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/check/*"
  to = "http://api.ipstack.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*"}
